# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Xcode ${{ matrix.xcode }}
    runs-on: ${{ matrix.runner-image }}
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#xcode
        include:
          - xcode: "14.1"
            runner-image: macOS-12
            name: "macOS 12, Xcode 14.1, Swift 5.7.1"
          - xcode: "14.0.1"
            runner-image: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7.0"
          - xcode: "13.4.1"
            runner-image: macOS-12
            name: "macOS 12, Xcode 13.4.1, Swift 5.6.1"
          - xcode: "13.3.1"
            runner-image: macOS-12
            name: "macOS 12, Xcode 13.3.1, Swift 5.6.0"
          - xcode: "13.2.1"
            runner-image: macOS-11
            name: "macOS 11, Xcode 13.2.1, Swift 5.5.2"
          - xcode: "13.1"
            runner-image: macOS-11
            name: "macOS 11, Xcode 13.1, Swift 5.5.1"
          - xcode: "13.0"
            runner-image: macOS-11
            name: "macOS 11, Xcode 13.0, Swift 5.5.0"
          - xcode: "12.5.1"
            runner-image: macOS-11
            name: "macOS 11, Xcode 12.5.1, Swift 5.4.2"
          - xcode: "12.4"
            runner-image: macOS-11
            name: "macOS 11, Xcode 12.4, Swift 5.3.2"
          - xcode: "11.7"
            runner-image: macOS-11
            name: "macOS 11, Xcode 11.7, Swift 5.2.something"
    steps:
    - uses: actions/checkout@v3
    - run: swift -version
    - name: run
      run: swift run test.swift
